#GCP - AppEngine
runtime: python39
env: standard

service: canaweb-ui

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|ico)(|\.map))$
    static_files: dist/CanaWebNG/\1
    upload: dist/(.*)(|\.map)

  - url: /(.*)
    static_files: dist/CanaWebNG/index.html
    upload: dist/CanaWebNG/index.html



# gcloud app deploy --project=dev-canaweb-firestore

