#GCP - AppEngine
runtime: python39
env: standard

service: canaweb-ui

handlers:
  - url: /
    static_files: dist/CanaWebNG/index.html
    upload: dist/CanaWebNG/index.html
  - url: /
    static_dir: dist/CanaWebNG



# gcloud app deploy --project=dev-canaweb-firestore

