steps:
  - name: "node:latest"
    entrypoint: "npm"
    args: ["install"]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo 'ENV: '${_SB_ENV}
        for f in ./src/environments/environment.*; do
          echo "Replace values in: ${f}"
          sed -i "s/_SB_ENV/${_SB_ENV}/g" $f
          sed -i "s/_BUILD_TIME/`date`/g" $f
          sed -i "s/_COMMIT_ID/${COMMIT_SHA}/g" $f
          sed -i "s/_BRANCH_NAME/${BRANCH_NAME}/g" $f
        done

  # Build production package
  - name: "node:latest"
    entrypoint: "npm"
    args: ["run", "build", "--configuration=production"]
    dir: "CanWebNG"


  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
